name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create debug build
      uses: gradle/gradle-build-action@v1
      with:
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: build
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Upload binaries to a release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/outputs/apk/a_github/debug/*.apk
        file_glob: true
        tag: ${{ steps.vars.outputs.sha_short }}
        overwrite: true
        body: ${{ github.event.head_commit.message }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: osu-droid-debug
        path: build/outputs/apk/a_github/debug