name: Update Gradle

on: workflow_dispatch

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - uses: rahulsom/gradle-up@v0.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}